ping:
    type: get
    path: ping
    controller: 'Acme\Api\Http\Controller\PingController@ping'

dashboard:
    type: get
    path: dashboards
    controller: 'Acme\Api\Http\Controller\DashboardController@index'
